### ISSUE TITLE
Unable to run example on android device

### ISSUE THREAD

**Issue by landonmr** [LeGoffMael/video_editor#26]
Any one succesfully run the example project on android.  I keep getting a link error when selecting a video from the video picker

```[✓] Flutter (Channel unknown, 2.2.0, on macOS 11.3.1 20E241 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.57.1)
[✓] Connected device (3 available)
```

Error
```D/flutter-ffmpeg(20024): Getting media information for /data/user/0/com.example.example/cache/image_picker4563386282795633928.mp4.
I/mobile-ffmpeg(20024): Loading mobile-ffmpeg.
E/AndroidRuntime(20024): FATAL EXCEPTION: AsyncTask #1
E/AndroidRuntime(20024): Process: com.example.example, PID: 20024
E/AndroidRuntime(20024): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime(20024): 	at android.os.AsyncTask$4.done(AsyncTask.java:399)
E/AndroidRuntime(20024): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
E/AndroidRuntime(20024): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
E/AndroidRuntime(20024): 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
E/AndroidRuntime(20024): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(20024): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(20024): 	at java.lang.Thread.run(Thread.java:919)
E/AndroidRuntime(20024): Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.example-xJN3eUWdoXXgIQ0SI1i6DA==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.example-xJN3eUWdoXXgIQ0SI1i6DA==/lib/arm64, /data/app/com.example.example-xJN3eUWdoXXgIQ0SI1i6DA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]] couldn't find "libmobileffmpeg_abidetect.so"
E/AndroidRuntime(20024): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
E/AndroidRuntime(20024): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
E/AndroidRuntime(20024): 	at java.lang.System.loadLibrary(System.java:1667)
E/AndroidRuntime(20024): 	at com.arthenica.mobileffmpeg.AbiDetect.<clinit>(AbiDetect.java:33)
E/AndroidRuntime(20024): 	at com.arthenica.mobileffmpeg.AbiDetect.getNativeAbi(Native Method)
E/AndroidRuntime(20024): 	at com.arthenica.mobileffmpeg.Config.<clinit>(Config.java:113)
E/AndroidRuntime(20024): 	at com.arthenica.mobileffmpeg.Config.nativeFFprobeExecute(Native Method)
E/AndroidRuntime(20024): 	at com.arthenica.mobileffmpeg.FFprobe.execute(FFprobe.java:55)
E/AndroidRuntime(20024): 	at com.arthenica.mobileffmpeg.FFprobe.getMediaInformationFromCommandArguments(FFprobe.java:123)
E/AndroidRuntime(20024): 	at com.arthenica.mobileffmpeg.FFprobe.getMediaInformation(FFprobe.java:86)
E/AndroidRuntime(20024): 	at com.arthenica.flutter.ffmpeg.FlutterFFmpegGetMediaInformationAsyncTask.doInBackground(FlutterFFmpegGetMediaInformationAsyncTask.java:51)
E/AndroidRuntime(20024): 	at com.arthenica.flutter.ffmpeg.FlutterFFmpegGetMediaInformationAsyncTask.doInBackground(FlutterFFmpegGetMediaInformationAsyncTask.java:36)
E/AndroidRuntime(20024): 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
E/AndroidRuntime(20024): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime(20024): 	... 3 more
I/Process (20024): Sending signal. PID: 20024 SIG: 9
Lost connection to device.
```

**Comment by landonmr** [comment]
I changed the gradle version to 
`distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-all.zip`

and I can pick a video from the video picker, crop, rotate from the example app.

Thanks for a great package!!!
