### ISSUE TITLE
FFmpeg exited with rc: 1

### ISSUE THREAD

**Issue by TohQiQi** [LeGoffMael/video_editor#36]
When I want to save or export the video, I get this:

```
D/flutter-ffmpeg( 2813): FFmpeg exited with rc: 1
I/flutter ( 2813): /data/user/0/com.example.apps/cache/file_picker/2021-04-20: No such file or directory
I/flutter ( 2813): ERROR ON EXPORT VIDEO (CODE 1)
```

**Comment by seel-channel** [comment]
Your path is wrong, because you can't use "-", "/", "\", etc. in filenames. You should replace your "-" to "_".

FFMPEG is so strict with the files path

**Comment by TohQiQi** [comment]
@seel-channel Thank you for your reply, the problem was solved after I change the path. I have one more question, before that my apps were only 28MB like that, after using this package my apps become 70MB. Is there any way to reduce the size of my apps?

**Comment by seel-channel** [comment]
FFMPEG Is a poor shit, because it's so heavy

**Comment by TohQiQi** [comment]
Ok, ， I just found one issue is I get errors in release mode. When I was in debug mode it works and no error. After I release the apps and want to run I get this error:


```
D/flutter-ffmpeg(10753): Getting media information for /data/user/0/com.example.apps/cache/file_picker/Screenrecorder-2021-05-19-15-53-57-515.mp4.
E/AndroidRuntime(10753): FATAL EXCEPTION: AsyncTask #2
E/AndroidRuntime(10753): Process: com.example.apps, PID: 10753
E/AndroidRuntime(10753): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime(10753):        at android.os.AsyncTask$4.done(AsyncTask.java:399)
E/AndroidRuntime(10753):        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
E/AndroidRuntime(10753):        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
E/AndroidRuntime(10753):        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
E/AndroidRuntime(10753):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(10753):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(10753):        at java.lang.Thread.run(Thread.java:919)
E/AndroidRuntime(10753): Caused by: java.lang.UnsatisfiedLinkError: Bad JNI version returned from JNI_OnLoad in "/data/app/com.example.apps-QO20kuBv0uYvExYVArrO7A==/lib/arm64/libmobileffmpeg.so": 0
E/AndroidRuntime(10753):        at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
E/AndroidRuntime(10753):        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
E/AndroidRuntime(10753):        at java.lang.System.loadLibrary(System.java:1667)
E/AndroidRuntime(10753):        at com.arthenica.mobileffmpeg.Config.<clinit>(Unknown Source:148)
E/AndroidRuntime(10753):        at com.arthenica.mobileffmpeg.Config.nativeFFprobeExecute(Native Method)
E/AndroidRuntime(10753):        at com.arthenica.mobileffmpeg.f.a(Unknown Source:0)
E/AndroidRuntime(10753):        at com.arthenica.mobileffmpeg.f.b(Unknown Source:0)
E/AndroidRuntime(10753):        at com.arthenica.mobileffmpeg.f.a(Unknown Source:48)
E/AndroidRuntime(10753):        at c.b.a.a.c.a(Unknown Source:21)
E/AndroidRuntime(10753):        at c.b.a.a.c.doInBackground(Unknown Source:2)
E/AndroidRuntime(10753):        at android.os.AsyncTask$3.call(AsyncTask.java:378)
E/AndroidRuntime(10753):        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime(10753):        ... 3 more

```

**Comment by TohQiQi** [comment]
@seel-channel Hi, I want to ask is this plugin support HD video?

**Comment by seel-channel** [comment]
The min-gpl-lts FFMPEG's package use x264 codcs (.MP4). And .MP4 support FullHD, if you use another non-gpl package the video quality going to be so bad.

[Issue #228 comment](https://github.com/tanersener/flutter-ffmpeg/issues/228#issuecomment-754658550) provide a explain for FFMPEG'S size

**Comment by TohQiQi** [comment]
ok thanks
